language: python

env:
  global:
    - ORGANIZATION="robberthalff"
    - EMAIL="deploy@travis-ci.org"
    - DEPLOYMENT_USER="traviscibot"
    - SOURCE_REPO="github.com/${ORGANIZATION}/robberthalff.git"
    - REPO="${ORGANIZATION}.github.io"
    - FILES="./public/*"
    - GH_REPO="github.com/${ORGANIZATION}/${REPO}.git"

after_success:
  - MESSAGE=$(git log -1 --pretty=%B)
  - git clone git://${SOURCE_REPO}
  - cd ${REPO}
  - rm -rf `ls | grep -v 'md$' | grep -v '.git'`
  - cp -f -r ../${FILES} ./
  - ls
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${DEPLOYMENT_USER}
  - git add .
  - git commit -m "${MESSAGE}"
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" master --force

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments

script:
  - hugo -s ./